version: "2.2"

dependencies:
  - project: madisonewebb/joda-time
  - project: madisonewebb/spring-petclinic
    dependencies:
      - project: madisonewebb/joda-time

default:
  build-command:
    current: mvn -B -U -DskipTests -s .github/maven-settings.xml deploy
    upstream: mvn -B -U -DskipTests -s .github/maven-settings.xml install
