version: "2.2"

dependencies:
  - project: madisonewebb/joda-time
    mapping:
      # When building joda-time as the DEPENDANT (reverse builds),
      # align joda-time's main to petclinic's master
      dependant:
        default:
          - source: main
            target: master

  - project: madisonewebb/spring-petclinic
    dependencies:
      - project: madisonewebb/joda-time
    mapping:
      # When building petclinic (dependant) against its dependency (joda-time),
      # align petclinic's master to joda-time's main
      dependencies:
        default:
          - source: master
            target: main
      # Optional: only needed if you trigger reverse builds from petclinic side
      dependant:
        default:
          - source: main
            target: master

default:
  build-command:
    current: mvn -B -U -DskipTests -s .github/maven-settings.xml deploy
    upstream: mvn -B -U -DskipTests -s .github/maven-settings.xml install
