name: Build Chain (Cross-repo)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      # No need to checkout the repo; the build-chain action does it itself
      # per the project docs.

      - name: Run Build Chain
        uses: kiegroup/github-action-build-chain@v3.5.9
        with:
          definition-file: ".github/build-chain.yml"   # <- make sure your file is here
          flow-type: "branch"
          starting-project: "madisonewebb/spring-petclinic"
          logger-level: "debug"
        env:
          # Use a PAT that has at least "Contents: Read" on BOTH repos.
          # (GITHUB_TOKEN often can't clone across repos.)
          GITHUB_TOKEN: ${{ secrets.GH_CLONE_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
