name: Build Chain (Cross-repo)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build Chain
        uses: kiegroup/github-action-build-chain@v3.5.9
        with:
          definition-file: ".ci/buildchain-config.yaml"
          flow-type: "branch"
          starting-project: "madisonewebb/spring-petclinic"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
