name: Build Chain (Cross-repo)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      # Checkout is required so the action can read the local definition-file path
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Build Chain
        uses: kiegroup/github-action-build-chain@v3.5.9
        with:
          definition-file: ".ci/buildchain-config.yaml"
          flow-type: "branch"
          starting-project: "madisonewebb/spring-petclinic"
          logger-level: "debug"
        env:
          # Use a PAT that has at least "Contents: Read" on BOTH repos.
          # (GITHUB_TOKEN often can't clone across repos.)
          GITHUB_TOKEN: ${{ secrets.GH_CLONE_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
